# Generated by Django 2.1.7 on 2019-04-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iniciosalimos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('idciudad', models.AutoField(db_column='IdCiudad', primary_key=True, serialize=False)),
                ('ciudad', models.CharField(db_column='Ciudad', max_length=45)),
                ('iddepartamento', models.PositiveIntegerField(db_column='IdDepartamento')),
            ],
            options={
                'db_table': 'ciudad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('idfavoritos', models.AutoField(db_column='Idfavoritos', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'favoritos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Funciones',
            fields=[
                ('idfuncion', models.AutoField(db_column='IdFuncion', primary_key=True, serialize=False)),
                ('idlugar', models.PositiveIntegerField(db_column='IdLugar')),
                ('funcion', models.CharField(blank=True, db_column='Funcion', max_length=37, null=True)),
                ('fecha', models.DateField(blank=True, db_column='Fecha', null=True)),
                ('hora', models.TimeField(blank=True, db_column='Hora', null=True)),
                ('idedad', models.PositiveIntegerField(blank=True, db_column='IdEdad', null=True)),
                ('fotofuncion', models.CharField(blank=True, db_column='FotoFuncion', max_length=11, null=True)),
            ],
            options={
                'db_table': 'funciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilesPerfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=255)),
                ('web', models.CharField(max_length=200)),
                ('imagen', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'perfiles_perfil',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='categorias',
            table='categorias',
        ),
        migrations.AlterModelTable(
            name='comentario',
            table='comentario',
        ),
        migrations.AlterModelTable(
            name='departamentos',
            table='departamentos',
        ),
        migrations.AlterModelTable(
            name='edades',
            table='edades',
        ),
        migrations.AlterModelTable(
            name='eventos',
            table='eventos',
        ),
        migrations.AlterModelTable(
            name='lugares',
            table='lugares',
        ),
    ]
