# Generated by Django 2.1.7 on 2019-04-30 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0002_remove_perfil_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='nombre',
        ),
    ]
