# Generated by Django 2.1.7 on 2019-05-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0003_remove_perfil_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
    ]
